### ISSUE TITLE
Why do you like Node.js so much that it hurts?

### ISSUE THREAD

**Issue by sindresorhus** [vadimdemedes/ama#15]

**Comment by vadimdemedes** [comment]
That is a goood question! I switched to Node.js after Ruby on Rails and I was instantly hooked. At that time, the reason was simple - compared to Rails I was in control of everything, I knew what is each line of code for and what it exactly does. I fell in love with an ability to use my favorite language on the server-side too. I fell in love with a simplicity of an ecosystem and dependencies. It was also interesting to ride on a wave of an emerging technology.
