### ISSUE TITLE
What do you study?

### ISSUE THREAD

**Issue by SamVerschueren** [vadimdemedes/ama#2]
If I'm not mistaken, you're a student? If not, what do you do for living? :)

**Comment by vadimdemedes** [comment]
Yes, I am a student, on a last semester, just waiting to get my diploma :) I am studying (not sure if I can say that about me) Computer Science in Poland.

I am blessed to do what I love for a living - programming. I got my first job at a startup 3 months before I went to university and was working non-stop since then! Fortunately, university was never a blocker for my work.
